spring:
  application:
    name: backend
    version: 0.0.0
  profiles:
    active: dev
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:none}
    password: ${MAIL_PASSWORD:none}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
    open-in-view: false

server:
  port: 8080
